all: lab.exe

lab.exe: 
	g++ -g Lab_Texture_MeshObj.cpp geometria.cpp ShaderMaker.cpp GestioneTesto.cpp gestioneTexture.cpp load_meshes_assimp.cpp -o lab.out -I/usr/include/assimp -I/usr/include/freetype2 -lglut -lGLU -lGL -lGLEW -lassimp -lfreetype





